# Netlify deployment configuration for Artist Portfolio

[build]
  # No build command needed for static HTML site
  publish = "."

[build.environment]
  # Environment variables (if needed in future)

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache control for assets
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.html"
  [headers.values]
    # Don't cache HTML files
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/styles/*"
  [headers.values]
    # Cache CSS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/scripts/*"
  [headers.values]
    # Cache JS files for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules
[[redirects]]
  from = "/portfolio"
  to = "/"
  status = 301

[[redirects]]
  from = "/gallery"
  to = "/"
  status = 301

# Error pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Form handling (for future contact forms)
# [[forms]]
#   name = "contact"